### ISSUE TITLE
enforcing memory limits with safety factor for k8s jobs

### ISSUE THREAD

**Issue by rptaylor** [HSF/harvester#116]
Hi @fbarreir 
I have tried the memory enforcement setting in AGIS for the dev cluster. It protects the nodes from crashing and OOM, but is a bit too aggressive on killing jobs.  The limit is set equal to the request for each job type.
```
    resources:
      limits:
        cpu: "8"
        memory: 16G
      requests:
        cpu: 7200m
        memory: 16G
```

In order to reasonably protect the nodes from misconfigured user jobs, but also avoid killing jobs too aggressively, we need a safety factor so that the limit exceeds the request.  This way jobs will be free to use extra  memory (as available) beyond what they requested, up to the limit.

Currently the memory requests for all the different job types are 2G, 4G, 16G, 32G.
I propose something like
`limit = request + min(2G, 0.25 * request)`
That way the limits would be 4G, 6G, 20G, 40G.   What do you think?

Perhaps the safety factor 0.25 could be a configurable parameter in AGIS, but either way it would be a big help because we need to protect the nodes from crashing/OOM in production (happened to ~ 6 nodes today).
