### ISSUE TITLE
set job and node environment variables for k8s

### ISSUE THREAD

**Issue by rptaylor** [HSF/harvester#144]
Hi @fbarreir 
To address https://github.com/PanDAWMS/pilot3/issues/51 and https://github.com/PanDAWMS/pilot3/issues/50 we can include this in the pod spec of a job:
```
      env:
        - name: PANDA_HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: K8S_JOB_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
```
I would suggest to take care of this in the Harvester k8s plugin, as it is coordinated with the pilot making it somewhat of a standard, and will be applicable to all queues. What do you think? We can go ahead and try it even if the pilot is not ready to read those environment variables yet. I have already tested this YAML in a pod and confirmed it works.

**Comment by rptaylor** [comment]
For that matter there are a number of other Harvester/Panda-related environment variables in the job YAML template:
https://github.com/PanDAWMS/harvester_configurations/blob/master/K8S/job_templates/CA-VICTORIA-K8S-T2_job.yaml#L40
Since they are somewhat standard and required for Harvester/pilot would it make sense to internalize them into the Harvester k8s plugin which creates the jobs?

**Comment by rptaylor** [comment]
@fbarreir Paul has set this up in the dev pilot; what do you think about putting this in the k8s Harvester plugin?
Thanks.

**Comment by fbarreir** [comment]
Hi @rptaylor , 

(CC @PalNilsson)

I've added `PANDA_HOSTNAME` and `K8S_JOB_ID`. If you want to test the dev pilot on your test queue, Paul needs to give you the URL and you can add it on CRIC.

For the other env variables, they were already in the code: https://github.com/HSF/harvester/blob/master/pandaharvester/harvestermisc/k8s_utils.py#L188. I guess I/we intended to clean them up from the yaml long time ago, but something else came up. I tested successfully to remove the env variables on one of my queues, but better try removing them from your TEST yaml first.

Regards,
Fernando

**Comment by fbarreir** [comment]
Just an update on this one. 

Paul released the change in the pilot last week. I suspect the value used for `K8S_JOB_ID` was problematic on one of my queues (the only K8S push queue), since 
```
        - name: K8S_JOB_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
```
is the **pod** id, not the **job** id. 

Harvester internally uses the **job** id and passes it to Panda server. 

Eventually panda server compares the values passed by Harvester and the Pilot, and fails jobs with mismatching ids. I changed harvester to pass the job id for `K8S_JOB_ID` to avoid the issue.
